# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-04 06:05
from __future__ import unicode_literals

import datetime
import beproud.django.basemodels.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyDatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ctime', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('utime', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DummyDatedModelManagerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('utime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DummyBaseManagerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('utime', models.DateTimeField()),
                ('del_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DummyBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ctime', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('utime', models.DateTimeField(auto_now=True, db_index=True)),
                ('del_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DummyBigAutoFieldModel',
            fields=[
                ('f', beproud.django.basemodels.fields.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DummyNonIntegerPKModel',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DummyChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.DummyBaseModel')),
                ('big_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.DummyBigAutoFieldModel')),
                ('non_int', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.DummyNonIntegerPKModel')),
            ],
        ),
        migrations.CreateModel(
            name='DummyPickleFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickled_object', beproud.django.basemodels.fields.PickledObjectField()),
            ],
        ),
    ]
